name: Pull Request Title Validation

description: Validate that the title of a pull request starts with FEATURE, FIX, TECH, or DOCS

inputs:
  repo-name:
    description: Name of the repository
    required: true

runs:
  using: "node12"
  main: "index.js"