name: Pull Request Title Validation

on:
  pull_request:
    types: [ opened, edited, synchronize ]

jobs:
  title_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}